from Tests.PageObject.Constants import EndPoint
from Tests.PageObject.RegisterPage import RegisterPage
from Tests.PageObject.locators import BasePageLocators


def test_guest_can_register(browser):
    page = RegisterPage(browser, EndPoint.base_link)
    page.open()
    page.click_on_button(*BasePageLocators.BUTTON_REGISTER)
    page.open_register_page()
    page.add_text_in_border_first_name()
    page.add_text_in_border_last_name()
    page.add_text_in_border_address()
    page.add_text_in_border_city()
    page.add_text_in_border_state()
    page.add_text_in_border_zipcode()
    page.add_text_in_border_phone()
    page.add_text_in_border_snn()
    page.add_text_in_border_username()
    page.add_text_in_border_password()
    page.add_text_in_border_confirm()
    page.press_the_button_register()
    page.should_not_be_button_register()


def test_guest_use_buttons_gohome_contact_aboutus_from_register_page(browser):
    page = RegisterPage(browser, EndPoint.base_link)
    page.open()
    page.click_on_button(*BasePageLocators.BUTTON_REGISTER)
    page.open_register_page()
    page.button_go_home()
    page.open()
    page.click_on_button(*BasePageLocators.BUTTON_REGISTER)
    page.button_go_contact()
    page.open()
    page.click_on_button(*BasePageLocators.BUTTON_REGISTER)
    page.button_go_aboutus()


class TestNegative:
    def test_negative_guest_can_register_address(self, browser):
        page = RegisterPage(browser, EndPoint.base_link)
        page.open()
        page.click_on_button(*BasePageLocators.BUTTON_REGISTER)
        page.open_register_page()
        page.add_text_in_border_first_name()
        page.add_text_in_border_last_name()
        page.add_text_in_border_city()
        page.add_text_in_border_state()
        page.add_text_in_border_zipcode()
        page.add_text_in_border_phone()
        page.add_text_in_border_snn()
        page.add_text_in_border_username()
        page.add_text_in_border_password()
        page.add_text_in_border_confirm()
        page.press_the_button_register()
        page.should_be_text_error()

    def test_negative_guest_can_register_city(self, browser):
        page = RegisterPage(browser, EndPoint.base_link)
        page.open()
        page.click_on_button(*BasePageLocators.BUTTON_REGISTER)
        page.open_register_page()
        page.add_text_in_border_first_name()
        page.add_text_in_border_last_name()
        page.add_text_in_border_address()
        page.add_text_in_border_state()
        page.add_text_in_border_zipcode()
        page.add_text_in_border_phone()
        page.add_text_in_border_snn()
        page.add_text_in_border_username()
        page.add_text_in_border_password()
        page.add_text_in_border_confirm()
        page.press_the_button_register()
        page.should_be_text_error()

    def test_negative_guest_can_register_state(self, browser):
        page = RegisterPage(browser, EndPoint.base_link)
        page.open()
        page.click_on_button(*BasePageLocators.BUTTON_REGISTER)
        page.open_register_page()
        page.add_text_in_border_first_name()
        page.add_text_in_border_last_name()
        page.add_text_in_border_address()
        page.add_text_in_border_city()
        page.add_text_in_border_zipcode()
        page.add_text_in_border_phone()
        page.add_text_in_border_snn()
        page.add_text_in_border_username()
        page.add_text_in_border_password()
        page.add_text_in_border_confirm()
        page.press_the_button_register()
        page.should_be_text_error()

    def test_negative_guest_can_register_zipcode(self, browser):
        page = RegisterPage(browser, EndPoint.base_link)
        page.open()
        page.click_on_button(*BasePageLocators.BUTTON_REGISTER)
        page.open_register_page()
        page.add_text_in_border_first_name()
        page.add_text_in_border_last_name()
        page.add_text_in_border_address()
        page.add_text_in_border_city()
        page.add_text_in_border_state()
        page.add_text_in_border_phone()
        page.add_text_in_border_snn()
        page.add_text_in_border_username()
        page.add_text_in_border_password()
        page.add_text_in_border_confirm()
        page.press_the_button_register()
        page.should_be_text_error()
