class TestPositive:
    def test_guest_can_register(self, page_register):
        page_register.press_the_button_go_to_register()
        page_register.should_be_panel()
        page_register.should_be_form()
        page_register.add_first_name()
        page_register.add_last_name()
        page_register.add_address()
        page_register.add_city()
        page_register.add_state()
        page_register.add_zipcode()
        page_register.add_phone()
        page_register.add_snn()
        page_register.add_username()
        page_register.add_password()
        page_register.add_confirm()
        page_register.press_the_button_register()
        page_register.should_not_be_button_register()

    def test_guest_use_buttons_gohome_contact_aboutus_from_register_page(self, page_register):
        page_register.press_the_button_go_to_register()
        page_register.should_be_panel()
        page_register.should_be_form()
        page_register.button_go_home()
        page_register.open()
        page_register.press_the_button_go_to_register()
        page_register.button_go_contact()
        page_register.open()
        page_register.press_the_button_go_to_register()
        page_register.button_go_aboutus()


class TestNegative:
    def test_negative_guest_can_register_address(self, page_register):
        page_register.press_the_button_go_to_register()
        page_register.should_be_panel()
        page_register.should_be_form()
        page_register.add_first_name()
        page_register.add_last_name()
        page_register.add_city()
        page_register.add_state()
        page_register.add_zipcode()
        page_register.add_phone()
        page_register.add_snn()
        page_register.add_username()
        page_register.add_password()
        page_register.add_confirm()
        page_register.press_the_button_register()
        page_register.should_be_text_error_address()

    def test_negative_guest_can_register_city(self, page_register):
        page_register.press_the_button_go_to_register()
        page_register.should_be_panel()
        page_register.should_be_form()
        page_register.add_first_name()
        page_register.add_last_name()
        page_register.add_address()
        page_register.add_state()
        page_register.add_zipcode()
        page_register.add_phone()
        page_register.add_snn()
        page_register.add_username()
        page_register.add_password()
        page_register.add_confirm()
        page_register.press_the_button_register()
        page_register.should_be_text_error_city()

    def test_negative_guest_can_register_state(self, page_register):
        page_register.press_the_button_go_to_register()
        page_register.should_be_panel()
        page_register.should_be_form()
        page_register.add_first_name()
        page_register.add_last_name()
        page_register.add_address()
        page_register.add_city()
        page_register.add_zipcode()
        page_register.add_phone()
        page_register.add_snn()
        page_register.add_username()
        page_register.add_password()
        page_register.add_confirm()
        page_register.press_the_button_register()
        page_register.should_be_text_error_state()

    def test_negative_guest_can_register_zipcode(self, page_register):
        page_register.press_the_button_go_to_register()
        page_register.should_be_panel()
        page_register.should_be_form()
        page_register.add_first_name()
        page_register.add_last_name()
        page_register.add_address()
        page_register.add_city()
        page_register.add_state()
        page_register.add_phone()
        page_register.add_snn()
        page_register.add_username()
        page_register.add_password()
        page_register.add_confirm()
        page_register.press_the_button_register()
        page_register.should_be_text_error_zipcode()
